/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsOfServiceRouteImport } from './routes/terms-of-service'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as HomeRouteImport } from './routes/home'
import { Route as ContactRouteImport } from './routes/Contact'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ZumbaRegistrationRouteImport } from './routes/zumba-registration'
import { Route as CarMeetRegistrationRouteImport } from './routes/car-meet-registration'

const TermsOfServiceRoute = TermsOfServiceRouteImport.update({
  id: '/terms-of-service',
  path: '/terms-of-service',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/Contact',
  path: '/Contact',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ZumbaRegistrationRoute = ZumbaRegistrationRouteImport.update({
  id: '/zumba-registration',
  path: '/zumba-registration',
  getParentRoute: () => rootRouteImport,
} as any)
const CarMeetRegistrationRoute = CarMeetRegistrationRouteImport.update({
  id: '/car-meet-registration',
  path: '/car-meet-registration',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/Contact': typeof ContactRoute
  '/home': typeof HomeRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/zumba-registration': typeof ZumbaRegistrationRoute
  '/car-meet-registration': typeof CarMeetRegistrationRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/Contact': typeof ContactRoute
  '/home': typeof HomeRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/zumba-registration': typeof ZumbaRegistrationRoute
  '/car-meet-registration': typeof CarMeetRegistrationRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/Contact': typeof ContactRoute
  '/home': typeof HomeRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/zumba-registration': typeof ZumbaRegistrationRoute
  '/car-meet-registration': typeof CarMeetRegistrationRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/Contact'
    | '/home'
    | '/privacy-policy'
    | '/terms-of-service'
    | '/zumba-registration'
    | '/car-meet-registration'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/Contact' | '/home' | '/privacy-policy' | '/terms-of-service' | '/zumba-registration' | '/car-meet-registration'
  id:
    | '__root__'
    | '/'
    | '/Contact'
    | '/home'
    | '/privacy-policy'
    | '/terms-of-service'
    | '/zumba-registration'
    | '/car-meet-registration'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContactRoute: typeof ContactRoute
  HomeRoute: typeof HomeRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  TermsOfServiceRoute: typeof TermsOfServiceRoute
  ZumbaRegistrationRoute: typeof ZumbaRegistrationRoute
  CarMeetRegistrationRoute: typeof CarMeetRegistrationRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms-of-service': {
      id: '/terms-of-service'
      path: '/terms-of-service'
      fullPath: '/terms-of-service'
      preLoaderRoute: typeof TermsOfServiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Contact': {
      id: '/Contact'
      path: '/Contact'
      fullPath: '/Contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/zumba-registration': {
      id: '/zumba-registration'
      path: '/zumba-registration'
      fullPath: '/zumba-registration'
      preLoaderRoute: typeof ZumbaRegistrationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/car-meet-registration': {
      id: '/car-meet-registration'
      path: '/car-meet-registration'
      fullPath: '/car-meet-registration'
      preLoaderRoute: typeof CarMeetRegistrationRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContactRoute: ContactRoute,
  HomeRoute: HomeRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  TermsOfServiceRoute: TermsOfServiceRoute,
  ZumbaRegistrationRoute: ZumbaRegistrationRoute,
  CarMeetRegistrationRoute: CarMeetRegistrationRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
